export const last_traded_price = "LTP";
export const p_and_l = "P/L";
export const current_value = "Current Value";
export const total_investment = "Total Investment";
export const todays_profit_and_loss = "Today's Profit & Loss";
export const profit_and_loss = "Profit & Loss";
export const upstox_hodling = "Upstox Holdings";
export const error_message = "Something_went_wrong, Please try again later!";
export const empty_list_message = "No holdings found!";
